# Generated by Django 3.0.8 on 2020-07-17 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(default='img/default.png', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='UseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_time', to='QAplatform.Room')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifying_code', models.CharField(max_length=10)),
                ('id_card', models.CharField(max_length=10)),
                ('name', models.CharField(default='未命名', max_length=12)),
                ('img', models.ImageField(default='img/default.jpg', upload_to='img')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('occupation', models.IntegerField(choices=[[0, '教务'], [1, '老师'], [2, '学生']], default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assistant', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QAplatform.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ManyToManyField(related_name='rooms', through='QAplatform.Status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='QAplatform.Room')),
            ],
        ),
    ]
