# Generated by Django 3.0.8 on 2020-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAplatform', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
